language: rust
before_install:
    - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
    - sudo apt-get update -o Dir::Etc::sourcelist="sources.list.d/terry_guo-gcc-arm-embedded-precise.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
install:
    - sudo apt-get install gcc-arm-none-eabi
script:
    - ./configure --host=arm-none-eabi
    - cargo build --target=$MCU --verbose
after_script:
    - cargo test --lib --verbose
    - (cd ./platformtree; cargo build --verbose; cargo test --verbose)
    - (cd ./macro_platformtree; cargo build --verbose; cargo test --verbose)
env:
  matrix:
    - MCU=lpc17xx
    - MCU=k20
    - MCU=stm32f4
    - MCU=stm32l1
    - MCU=tiva_c
